name: Web Testing CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@1

        with:
          ruby-version: $(cat .ruby-version)

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Tests through rake's default task
        run: bundle exec rake test
