# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        # uses: ruby/setup-ruby@v1
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: '3.2.2'

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Tests through rake's default task
        run: bundle exec rake test

      - name: Upload Minitest Reports
        uses: actions/upload-artifact@v4.1.0
        with:
          name: minitest-reports
          path: test/html_reports # Change this to the directory where Minitest reports are generated


  view-reports:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download Minitest Reports
        uses: actions/download-artifact@v2
        with:
          name: minitest-reports
          path: test/reports-html # Change this to the same path used in the upload step

      - name: View Minitest Reports
        run: |
          cat test/reports_html/*.html